### ISSUE TITLE
Supported locales

### ISSUE THREAD

**Issue by IP-Developer** [Lykegenes/laravel-locale-switcher#8]
I think this package should have a list (and be limited to that list) of available app locales in config. There is a problem that via URL I can set the application to use any locale. It breakes the app in my case (only 2 supported locales, but I can set any locale via URL). There is a package where this is done, https://github.com/mcamara/laravel-localization

**Comment by patricksamson** [comment]
Sorry for the delay, I just finished my exams! 
It's in the works, I found a list of locales and I just need to properly integrate it to the package

**Comment by patricksamson** [comment]
Done! See v1.2.0
